# Generated by Django 4.1.3 on 2022-12-12 11:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import farmers_market.companies.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='news', validators=[farmers_market.companies.validators.validate_image])),
                ('publication', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
