# Generated by Django 4.1.3 on 2022-12-07 11:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import farmers_market.companies.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('logo', models.ImageField(upload_to='', validators=[farmers_market.companies.validators.validate_image])),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('date_formed', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
