# Generated by Django 4.1.3 on 2022-12-08 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import farmers_market.companies.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='mediafiles', validators=[farmers_market.companies.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
