# Generated by Django 4.1.3 on 2022-12-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
